server:
  port: 80

eureka:
  client:
    egister-with-eureka: true
    etch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

#ribbon:
#  ReadTimeout: 5000       #建立链接超时时间
#  ConnectTimeout: 5000    #建立链接后读取资源时间

#logging:
#  level:
#    com.lqq.springcloud.server.PaymentFeignService: debug    #Feign日志以什么级别监控接口
