server:
  port: 80

eureka:
  client:
    egister-with-eureka: true
    etch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

feign:
  httpclient:
    enabled: true